### PR TITLE
docs: update to install windows c++ build tools for siphash-cffi package

### PR DESCRIPTION
**Pull request by gordon-epc**
In order to run from source on a Windows setup, I needed to install "Build Tools for Visual Studio 2019" with the "C++ build tools" option. Update the `readme.rst` accordingly.

### CODE REVIEW

**Comment by gordon-epc** [comment]
The build tools for visual studio were necessary to build the `siphash-cffi` package.

**Comment by altendky** [comment]
I think the issue is a missing `--extra-index-url`.  This seems to have first been added in https://github.com/altendky/pm/commit/18cb6a680ea705f822d02d7d5f6270ec529b8ef2#diff-ffb9a8aa35f8e58dd818a724713720da25a2847e19d36b4bbf5da7d5744415e0 then incorrectly removed in https://github.com/altendky/pm/commit/f709166c4fcd29660b0088d37d0a6c35998bd52e#diff-ffb9a8aa35f8e58dd818a724713720da25a2847e19d36b4bbf5da7d5744415e0.

For context see https://github.com/kpdemetriou/siphash-cffi/issues/3#issuecomment-626090348.

**Review by altendky — APPROVED** [review]
The PR probably deserves a different name now.  But, I guess this worked for you?  Looks ok to me, though I didn't test it.

**Comment by gordon-epc** [comment]
Yes, I tested and it worked. It took some effort to remove everything that the Windows build tools installed.

**Pull request merged**
